---
platform: linux

image_resource:
  type: docker-image
  source: { repository: pcfbosh/minimal }

inputs:
- name: pcf-bosh-ci
- name: terraform-state

outputs:
- name: terraform-db-vars

run:
  path: pcf-bosh-ci/tasks/generate-terraform-db-vars.sh
