---
platform: linux

image_resource:
  type: docker-image
  source: { repository: pcfbosh/aws-ruby }

inputs:
- name: pcf-bosh-ci
- name: penguin-ci
- name: bosh-vars-store
- name: terraform-state
- name: ipsec-zip

run:
  path: pcf-bosh-ci/tasks/update-runtime-config.sh
