---
resource_types:
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource

- name: gcs-resource
  type: docker-image
  source:
    repository: frodenas/gcs-resource

- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:

#########################
# PCF BOSH Repositories #
#########################

- name: pcf-bosh-ci
  type: git
  source:
    uri: https://github.com/pivotal-cf/pcf-bosh-ci
    branch: master

- name: cloud-config
  type: git
  source:
    uri: https://github.com/pivotal-cf/p-ert-bosh-experiment
    branch: {{p-ert-branch}}
    paths: [gcp/cloud-config.yml]

- name: p-ert-bosh-experiment
  type: git
  source:
    uri: https://github.com/pivotal-cf/p-ert-bosh-experiment
    branch: {{p-ert-branch}}
    ignore_paths: [gcp/cloud-config.yml]

- name: terraforming-gcp
  type: git
  source:
    uri: https://github.com/pivotal-cf/pcf-bosh-terraforming-gcp
    branch: master

###################
# CF Repositories #
###################

- name: cf-deployment
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-deployment
    branch: master

    # This variable allows users to decide to lock to cf-deployment
    # version 0.0.0 or to float on the latest commit to master. By
    # setting the variable to "tag_filter", cf-deployment will be
    # locked to 0.0.0.
    {{set_to_tag_filter_to_lock_cf_deployment}}: "0\\.0\\.0"

- name: cf-acceptance-tests
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-acceptance-tests
    branch: master

- name: bosh-deployment
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh-deployment
    branch: master

######################
# MySQL Repositories #
######################

- name: p-mysql-deployment
  type: git
  source:
    uri: git@github.com:pivotal-cf-experimental/p-mysql-deployment
    branch: master
    private_key: {{p-mysql-deployment_deploy_key}}

##################
# p-MySQL Assets #
##################

- name: mysql-monitoring-release
  type: s3
  source:
    bucket: mysql-monitoring-releases
    access_key_id: {{mysql_releases_access_key_id}}
    secret_access_key: {{mysql_releases_secret_access_key}}
    regexp: final/mysql-monitoring-(\d\.\d\.\d).tgz

##############
# PCF Assets #
##############

- name: closed-source-releases-zip
  type: gcs-resource
  source:
    bucket: pcf-bosh-ci
    json_key: {{google_json_key}}
    versioned_file: closed-source-releases.zip

######################
# External Resources #
######################

- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource

#########################
# Pipeline Global State #
#########################

- name: terraform-vars
  type: gcs-resource
  source:
    bucket: pcf-bosh-ci
    json_key: {{google_json_key}}
    versioned_file: terraform.tfvars.yml

##################
# Pipeline State #
##################

- name: terraform-state
  type: terraform
  source:
    storage:
      bucket: pcf-bosh-ci
      bucket_path: terraform-environments
      access_key_id: {{gcs_access_key_id}}
      secret_access_key: {{gcs_secret_access_key}}
      endpoint: storage.googleapis.com
  delete_on_failure: true

- name: bosh-state
  type: gcs-resource
  source:
    bucket: pcf-bosh-ci
    json_key: {{google_json_key}}
    versioned_file: '{{env_name}}-bosh-state.json'

- name: bosh-vars-store
  type: gcs-resource
  source:
    bucket: pcf-bosh-ci
    json_key: {{google_json_key}}
    versioned_file: '{{env_name}}-bosh-vars-store.yml'

- name: cf-vars-store
  type: gcs-resource
  source:
    bucket: pcf-bosh-ci
    json_key: {{google_json_key}}
    versioned_file: '{{env_name}}-cf-vars-store.yml'

- name: mysql-vars-store
  type: gcs-resource
  source:
    bucket: pcf-bosh-ci
    json_key: {{google_json_key}}
    versioned_file: '{{env_name}}-mysql-vars-store.yml'

jobs:

##################
# Infrastructure #
##################

- name: terraform-up
  plan:
  - aggregate:
    - get: terraforming-gcp
      trigger: true
    - get: terraform-vars
      trigger: true
    - get: terraform
      trigger: true
  - put: terraform-state
    params:
      var_file: terraform-vars/terraform.tfvars.yml
      terraform_source: terraforming-gcp
      delete_on_failure: true
      env_name: {{env_name}}

########
# BOSH #
########

- name: deploy-director
  plan:
  - aggregate:
    - get: pcf-bosh-ci
    - get: bosh-deployment
      version:
        ref: ccca4c9f7bcdd0f217c8c3adf186648c52b3b137
    - get: bosh-state
    - get: bosh-vars-store
    - get: terraform-state
      trigger: true
      passed: [terraform-up]
  - task: deploy-director
    file: pcf-bosh-ci/tasks/deploy-director.yml
    params:
      GOOGLE_JSON_KEY: {{google_json_key}}
    ensure:
      aggregate:
      - put: bosh-state
        params:
          file: new-bosh-state/*
      - put: bosh-vars-store
        params:
          file: new-bosh-vars-store/*

- name: upload-cloud-config
  plan:
  - aggregate:
    - get: pcf-bosh-ci
    - get: cloud-config
      trigger: true
    - get: bosh-vars-store
      trigger: true
      passed: [deploy-director]
    - get: terraform-state
      trigger: true
      passed: [deploy-director]
  - task: upload-cloud-config
    file: pcf-bosh-ci/tasks/upload-cloud-config.yml

- name: upload-stemcell
  plan:
  - aggregate:
    - get: pcf-bosh-ci
    - get: cf-deployment
      trigger: true
    - get: bosh-vars-store
      trigger: true
      passed: [deploy-director]
    - get: terraform-state
      passed: [deploy-director]
  - task: stemcell-url-from-cf-deployment
    file: pcf-bosh-ci/tasks/stemcell-url-from-cf-deployment.yml
    params:
      NAME: bosh-google-kvm-ubuntu-trusty-go_agent
  - task: upload-stemcell
    file: pcf-bosh-ci/tasks/upload-stemcell.yml

#################
# Cloud Foundry #
#################

- name: deploy-ert
  serial: true
  serial_groups: [cf-bosh-deployment]
  plan:
  - aggregate:
    - get: pcf-bosh-ci
    - get: cf-deployment
      trigger: true
      passed: [upload-stemcell]
    - get: p-ert
      resource: p-ert-bosh-experiment
      trigger: true
    - get: cf-vars-store
    - get: closed-source-releases-zip
    - get: bosh-vars-store
      trigger: true
      passed: [upload-cloud-config, upload-stemcell]
    - get: terraform-state
      passed: [upload-cloud-config, upload-stemcell]
  - task: extract-closed-source-releases
    file: pcf-bosh-ci/tasks/extract-closed-source-releases.yml
  - task: deploy-ert
    file: pcf-bosh-ci/tasks/deploy-ert.yml
    params:
      SMTP_HOST_NAME: {{smtp_host_name}}
      SMTP_HOST_PORT: {{smtp_host_port}}
      SMTP_SENDER_USERNAME: {{smtp_sender_username}}
      SMTP_SENDER_PASSWORD: {{smtp_sender_password}}
    ensure:
        put: cf-vars-store
        params:
          file: new-cf-vars-store/*

###################
# Default Errands #
###################

- name: push-apps-manager
  serial: true
  serial_groups: [cf-bosh-deployment]
  plan:
  - aggregate:
    - get: pcf-bosh-ci
    - get: bosh-vars-store
      passed: [deploy-ert]
    - get: terraform-state
      passed: [deploy-ert]
    - get: cf-vars-store
      trigger: true
      passed: [deploy-ert]
    - get: cf-deployment
      passed: [deploy-ert]
  - task: push-apps-manager
    file: pcf-bosh-ci/tasks/run-errand.yml
    params:
      DEPLOYMENT: cf
      ERRAND: push-apps-manager

- name: deploy-notifications
  serial: true
  serial_groups: [cf-bosh-deployment]
  plan:
  - aggregate:
    - get: pcf-bosh-ci
    - get: bosh-vars-store
      passed: [deploy-ert]
    - get: terraform-state
      passed: [deploy-ert]
    - get: cf-vars-store
      trigger: true
      passed: [deploy-ert]
    - get: cf-deployment
      passed: [deploy-ert]
  - task: deploy-notifications
    file: pcf-bosh-ci/tasks/run-errand.yml
    params:
      DEPLOYMENT: cf
      ERRAND: deploy-notifications

- name: deploy-notifications-ui
  serial: true
  serial_groups: [cf-bosh-deployment]
  plan:
  - aggregate:
    - get: pcf-bosh-ci
    - get: bosh-vars-store
      passed: [deploy-notifications]
    - get: terraform-state
      passed: [deploy-notifications]
    - get: cf-vars-store
      trigger: true
      passed: [deploy-notifications]
    - get: cf-deployment
      passed: [deploy-notifications]
  - task: deploy-notifications-ui
    file: pcf-bosh-ci/tasks/run-errand.yml
    params:
      DEPLOYMENT: cf
      ERRAND: deploy-notifications-ui

- name: deploy-autoscaling
  serial: true
  serial_groups: [cf-bosh-deployment]
  plan:
  - aggregate:
    - get: pcf-bosh-ci
    - get: bosh-vars-store
      passed: [deploy-ert]
    - get: terraform-state
      passed: [deploy-ert]
    - get: cf-vars-store
      trigger: true
      passed: [deploy-ert]
    - get: cf-deployment
      passed: [deploy-ert]
  - task: deploy-autoscaling
    file: pcf-bosh-ci/tasks/run-errand.yml
    params:
      DEPLOYMENT: cf
      ERRAND: deploy-autoscaling

- name: autoscaling-register-broker
  serial: true
  serial_groups: [cf-bosh-deployment]
  plan:
  - aggregate:
    - get: pcf-bosh-ci
    - get: bosh-vars-store
      passed: [deploy-autoscaling]
    - get: terraform-state
      passed: [deploy-autoscaling]
    - get: cf-vars-store
      trigger: true
      passed: [deploy-autoscaling]
    - get: cf-deployment
      passed: [deploy-autoscaling]
  - task: autoscaling-register-broker
    file: pcf-bosh-ci/tasks/run-errand.yml
    params:
      DEPLOYMENT: cf
      ERRAND: autoscaling-register-broker

- name: push-pivotal-account
  serial: true
  serial_groups: [cf-bosh-deployment]
  plan:
  - aggregate:
    - get: pcf-bosh-ci
    - get: bosh-vars-store
      passed: [deploy-ert]
    - get: terraform-state
      passed: [deploy-ert]
    - get: cf-vars-store
      trigger: true
      passed: [deploy-ert]
    - get: cf-deployment
      passed: [deploy-ert]
  - task: push-pivotal-account
    file: pcf-bosh-ci/tasks/run-errand.yml
    params:
      DEPLOYMENT: cf
      ERRAND: push-pivotal-account

####################
# Recovery Errands #
####################

- name: mysql-bootstrap
  serial: true
  serial_groups: [cf-bosh-deployment]
  plan:
  - aggregate:
    - get: pcf-bosh-ci
    - get: bosh-vars-store
      passed: [deploy-ert]
    - get: terraform-state
      passed: [deploy-ert]
    - get: cf-vars-store
      passed: [deploy-ert]
    - get: cf-deployment
      passed: [deploy-ert]
  - task: mysql-bootstrap
    file: pcf-bosh-ci/tasks/run-errand.yml
    params:
      DEPLOYMENT: cf
      ERRAND: mysql-bootstrap

- name: mysql-rejoin-unsafe
  serial: true
  serial_groups: [cf-bosh-deployment]
  plan:
  - aggregate:
    - get: pcf-bosh-ci
    - get: bosh-vars-store
      passed: [deploy-ert]
    - get: terraform-state
      passed: [deploy-ert]
    - get: cf-vars-store
      passed: [deploy-ert]
    - get: cf-deployment
      passed: [deploy-ert]
  - task: mysql-rejoin-unsafe
    file: pcf-bosh-ci/tasks/run-errand.yml
    params:
      DEPLOYMENT: cf
      ERRAND: mysql-rejoin-unsafe

#########
# Tests #
#########

- name: smoke-tests
  serial_groups: [cf-bosh-deployment]
  plan:
  - aggregate:
    - get: pcf-bosh-ci
    - get: bosh-vars-store
      passed: &errands [push-apps-manager, autoscaling-register-broker] # deploy-notifications-ui
    - get: cf-vars-store
      trigger: true
      passed: *errands
    - get: terraform-state
      passed: *errands
  - task: run-smoke-tests
    file: pcf-bosh-ci/tasks/run-errand.yml
    params:
      DEPLOYMENT: cf
      ERRAND: smoke-tests

- name: run-cats
  plan:
  - aggregate:
    - get: pcf-bosh-ci
    - get: cf-acceptance-tests
      version: {ref: 8691a293fe613ee817e69d6760deec40820af421}
    - get: cf-vars-store
      trigger: true
      passed: *errands
    - get: terraform-state
      passed: *errands
  - task: enable-diego-docker
    file: pcf-bosh-ci/tasks/enable-diego-docker.yml
  - task: run-cats
    file: pcf-bosh-ci/tasks/run-cats.yml

- name: run-rats
  plan:
  - aggregate:
    - get: pcf-bosh-ci
    - get: cf-acceptance-tests
    - get: cf-deployment
      passed: *errands
    - get: cf-vars-store
      trigger: true
      passed: *errands
    - get: terraform-state
      passed: *errands
  - task: fetch-routing-release
    file: pcf-bosh-ci/tasks/fetch-routing-release.yml
  - task: run-rats
    file: pcf-bosh-ci/tasks/run-rats.yml

#########
# MySQL #
#########

- name: upload-closed-source-mysql-releases
  serial: true
  plan:
  - aggregate:
    - get: pcf-bosh-ci
    - get: mysql-monitoring-release
      trigger: true
    - get: bosh-vars-store
      trigger: true
      passed: [deploy-director]
    - get: terraform-state
      passed: [deploy-director]
  - task: upload-mysql-monitoring-release
    file: pcf-bosh-ci/tasks/upload-release.yml
    input_mapping:
      release: mysql-monitoring-release

- name: deploy-mysql
  serial: true
  serial_groups: [mysql-bosh-deployment]
  plan:
  - aggregate:
    - get: pcf-bosh-ci
    - get: p-mysql-deployment
      trigger: true
    - get: mysql-vars-store
    - get: cf-vars-store
      passed: [deploy-ert]
    - get: bosh-vars-store
      trigger: true
      passed: [deploy-ert]
    - get: terraform-state
      passed: [deploy-ert]
  - task: deploy-mysql
    file: pcf-bosh-ci/tasks/deploy-mysql.yml
    ensure:
        put: mysql-vars-store
        params:
          file: new-mysql-vars-store/*

- name: broker-registrar
  serial: true
  serial_groups: [mysql-bosh-deployment]
  plan:
  - aggregate:
    - get: pcf-bosh-ci
    - get: bosh-vars-store
      passed: [deploy-mysql]
    - get: terraform-state
      passed: [deploy-mysql]
    - get: mysql-vars-store
      trigger: true
      passed: [deploy-mysql]
  - task: broker-registrar
    file: pcf-bosh-ci/tasks/run-errand.yml
    params:
      DEPLOYMENT: p-mysql
      ERRAND: broker-registrar

- name: mysql-smoke-tests
  serial: true
  serial_groups: [mysql-bosh-deployment]
  plan:
  - aggregate:
    - get: pcf-bosh-ci
    - get: bosh-vars-store
      passed: [broker-registrar]
    - get: terraform-state
      passed: [broker-registrar]
    - get: mysql-vars-store
      trigger: true
      passed: [broker-registrar]
  - task: smoke-tests
    file: pcf-bosh-ci/tasks/run-errand.yml
    params:
      DEPLOYMENT: p-mysql
      ERRAND: smoke-tests

################
# Delete MySQL #
################

- name: delete-mysql
  serial: true
  serial_groups: [mysql-bosh-deployment]
  plan:
  - aggregate:
    - get: pcf-bosh-ci
    - get: bosh-vars-store
      passed: [deploy-mysql]
    - get: terraform-state
      passed: [deploy-mysql]
  - task: broker-deregistrar
    file: pcf-bosh-ci/tasks/run-errand.yml
    params:
      DEPLOYMENT: p-mysql
      ERRAND: broker-deregistrar
  - task: delete-mysql-deployment
    file: pcf-bosh-ci/tasks/delete-deployment.yml
    params:
      DEPLOYMENT: p-mysql

##############
# Delete ERT #
##############

- name: delete-ert
  serial: true
  serial_groups: [cf-bosh-deployment]
  plan:
  - aggregate:
    - get: pcf-bosh-ci
    - get: bosh-vars-store
      passed: [delete-mysql]
    - get: terraform-state
      passed: [delete-mysql]
  - task: delete-ert-deployment
    file: pcf-bosh-ci/tasks/delete-deployment.yml
    params:
      DEPLOYMENT: cf
